name = "sorou"
main = "src/index.ts"
compatibility_date = "2025-01-01"
account_id = "${CLOUDFLARE_ACCOUNT_ID}"

[vars]
ADMIN_PASSWORD = ""

[[d1_databases]]
binding = "DB"
database_name = "sorou-db"
database_id = "sorou-db-dev"
